MAP_WIDTH = 10
MAP_HEIGHT = 10

ROOM_WIDTH = 7
ROOM_HEIGHT = 7
DOOR_POSITION = 3

WALL_WIDTH = 32

TILE_WIDTH = 64
TILE_HEIGHT = 64


SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480


PLAYER_SPEED = 240
PLAYER_FRAME_ROTATION = 120
PLAYER_WIDTH = 48
PLAYER_HEIGHT = 48
PLAYER_CROP_LEFT = 10
PLAYER_CROP_RIGHT = 6
PLAYER_CROP_TOP = 2
PLAYER_CROP_BOTTOM = -9


MIN_DISTANCE_WC_BED = 10
MAX_DISTANCE_WC_BED = 12
CLOSING_DOORS_SWAPS = 75
MAX_CLOSING_DOORS = 30


MONSTER_SPAWN_INTERVAL = 90
MIN_MONSTER_DISTANCE = ROOM_WIDTH * TILE_WIDTH + ROOM_HEIGHT * TILE_HEIGHT
MONSTER_SPEED = 40
MONSTER_RANDOM_WALK = 0.3
MONSTER_MOVE_INTERVAL = 5
MONSTER_ANNOUNCE_INTERVAL = 10
MONSTER_WARNING_INTERVAL = 2
